In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
%matplotlib inline
from word2number import w2n

In [3]:
df = pd.read_csv('homeprices.csv')
df.head()

area bedrooms  age   price
0  2600        3   20  550000
1  3000        4   15  565000
2  3200            18  610000
3  3600        3   30  595000
4  4000        5    8  760000

In [4]:
#calculate median
df.bedrooms = pd.to_numeric(df.bedrooms, errors='coerce').astype('Int64')

df.bedrooms.median()

3.5

In [5]:
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

3

In [6]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df.head()

area  bedrooms  age   price
0  2600         3   20  550000
1  3000         4   15  565000
2  3200         3   18  610000
3  3600         3   30  595000
4  4000         5    8  760000

In [7]:
reg = linear_model.LinearRegression()
reg.fit(df[['area', 'bedrooms', 'age']], df.price)

LinearRegression()

In [8]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [9]:
reg.intercept_

383724.99999999994

In [10]:
reg.predict([[3000, 3, 40]])

c:\Users\hamdy\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([444400.])

In [11]:
#y = m1*x1 + m2*x2 + m3*x3

137.25*3000 + -26025*3 + -6825*40 + 383724.99999999994

444399.99999999994

In [12]:
reg.predict([[2500, 4, 5]])

c:\Users\hamdy\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([588625.])

# Exercise


#### Predict salaries for furture candidates
2 yr experience, 9 test score, 6 interview score

12 yr experience, 10 test score, 10 interview score



In [13]:
df = pd.read_csv('testscore.csv')

In [14]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [15]:
df.experience = df.experience.fillna('zero')

In [19]:
df.experience = df.experience.apply(w2n.word_to_num)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [21]:
median_test_score = math.floor(df['test_score(out of 10)'].mean())
median_test_score

7

In [22]:
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(median_test_score)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [26]:
reg = linear_model.LinearRegression()
reg.fit(df[['experience', 'test_score(out of 10)', 'interview_score(out of 10)']], df['salary($)'])

LinearRegression()

In [28]:
reg.predict([[2, 9, 6]])

c:\Users\hamdy\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53713.86677124])

In [29]:
reg.predict([[12,10,10]])

c:\Users\hamdy\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([93747.79628651])