In [17]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [18]:
iris = load_iris()

In [19]:
from sklearn.model_selection import KFold
kf = KFold(n_splits = 5)
kf

KFold(n_splits=5, random_state=None, shuffle=False)

In [20]:
from sklearn.model_selection import StratifiedKFold
skf = StratifiedKFold(n_splits = 3)
skf

StratifiedKFold(n_splits=3, random_state=None, shuffle=False)

Cross Value Function import from sklearn

In [21]:
from sklearn.model_selection import cross_val_score

In [22]:
cross_val_score(LogisticRegression(), iris.data, iris.target)

c:\Users\hamdy\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [23]:
cross_val_score(SVC(), iris.data, iris.target)

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [24]:
cross_val_score(RandomForestClassifier(), iris.data, iris.target)

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

Parameter Tuning for most accurate model (Logistic regression)

In [25]:
cross_val_score(LogisticRegression(C=20), iris.data, iris.target)

c:\Users\hamdy\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\hamdy\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stab

array([0.96666667, 1.        , 0.96666667, 0.93333333, 1.        ])